"""add prompt tracking score fields

Revision ID: 19303c408a51
Revises: 
Create Date: 2026-03-31 14:58:37.125806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19303c408a51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_tracking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_score', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('score_band', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('opportunity_label', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('brand_position', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('competitor_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('source_support', sa.String(length=50), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('is_white_label_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_white_label_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('prompt_tracking', schema=None) as batch_op:
        batch_op.drop_column('source_support')
        batch_op.drop_column('competitor_count')
        batch_op.drop_column('brand_position')
        batch_op.drop_column('opportunity_label')
        batch_op.drop_column('score_band')
        batch_op.drop_column('prompt_score')

    # ### end Alembic commands ###
