"""add agency white-label fields to user

Revision ID: 2b850d327704
Revises: 563ab7b258a5
Create Date: 2026-05-09 15:34:59.111579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b850d327704'
down_revision = '563ab7b258a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agency_tagline', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('agency_website', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('agency_footer', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('agency_disclaimer', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('agency_logo_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('agency_logo_filename')
        batch_op.drop_column('agency_disclaimer')
        batch_op.drop_column('agency_footer')
        batch_op.drop_column('agency_website')
        batch_op.drop_column('agency_tagline')

    # ### end Alembic commands ###
