"""add brand_kit_approved_at column

Revision ID: 313bc65d013c
Revises: a0b17aa51f73
Create Date: 2026-05-09 18:41:08.289432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313bc65d013c'
down_revision = 'a0b17aa51f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_kit_approved_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('brand_kit_approved_at')

    # ### end Alembic commands ###
