"""add woocommerce_connections

Revision ID: 330f7f6293f5
Revises: 2b850d327704
Create Date: 2026-05-09 15:49:08.422102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330f7f6293f5'
down_revision = '2b850d327704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('woocommerce_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('store_url', sa.String(length=500), nullable=False),
    sa.Column('consumer_key', sa.Text(), nullable=False),
    sa.Column('consumer_secret', sa.Text(), nullable=False),
    sa.Column('last_audit_payload', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_woo_user_client')
    )
    with op.batch_alter_table('woocommerce_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_woocommerce_connections_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_woocommerce_connections_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('woocommerce_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_woocommerce_connections_user_id'))
        batch_op.drop_index(batch_op.f('ix_woocommerce_connections_client_id'))

    op.drop_table('woocommerce_connections')
    # ### end Alembic commands ###
