"""add business profile fields to client

Revision ID: 40a9ccb99afa
Revises: c67f89c5d1a9
Create Date: 2026-05-09 16:07:40.184703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a9ccb99afa'
down_revision = 'c67f89c5d1a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('founded_year', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('google_rating', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('google_review_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('business_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('business_profile_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('business_profile_updated_at')
        batch_op.drop_column('business_summary')
        batch_op.drop_column('google_review_count')
        batch_op.drop_column('google_rating')
        batch_op.drop_column('founded_year')

    # ### end Alembic commands ###
