"""add ga property + payload columns to gsc connection

Revision ID: 563ab7b258a5
Revises: c5a659174965
Create Date: 2026-05-09 15:30:17.243918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563ab7b258a5'
down_revision = 'c5a659174965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_search_console_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ga_property_id', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('ga_payload', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ga_synced_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_search_console_connections', schema=None) as batch_op:
        batch_op.drop_column('ga_synced_at')
        batch_op.drop_column('ga_payload')
        batch_op.drop_column('ga_property_id')

    # ### end Alembic commands ###
