"""team seats: extra_seats + team_owner_id + team_invites

Revision ID: 5a7535e7f9bb
Revises: c12136a63deb
Create Date: 2026-05-09 10:06:36.338833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a7535e7f9bb'
down_revision = 'c12136a63deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_invites_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_invites_token'), ['token'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_seats', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('team_owner_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_team_owner_id'), ['team_owner_id'], unique=False)
        batch_op.create_foreign_key('fk_users_team_owner_id', 'users', ['team_owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_team_owner_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_team_owner_id'))
        batch_op.drop_column('team_owner_id')
        batch_op.drop_column('extra_seats')

    with op.batch_alter_table('team_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_invites_token'))
        batch_op.drop_index(batch_op.f('ix_team_invites_owner_user_id'))

    op.drop_table('team_invites')
    # ### end Alembic commands ###
