"""add public share token to client

Revision ID: 6292cb3b78ac
Revises: 313bc65d013c
Create Date: 2026-05-09 18:43:14.838780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6292cb3b78ac'
down_revision = '313bc65d013c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_share_token', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('public_share_created_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_clients_public_share_token'), ['public_share_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_public_share_token'))
        batch_op.drop_column('public_share_created_at')
        batch_op.drop_column('public_share_token')

    # ### end Alembic commands ###
