"""add prompt_check_snapshots table

Revision ID: 6d8a28a2e2b5
Revises: 8db89666f708
Create Date: 2026-05-09 00:29:25.650396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8a28a2e2b5'
down_revision = '8db89666f708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_check_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_tracking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('engine', sa.String(length=60), nullable=True),
    sa.Column('brand_mentioned', sa.Boolean(), nullable=False),
    sa.Column('brand_position', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('answer_type', sa.String(length=60), nullable=True),
    sa.Column('competitors_mentioned', sa.JSON(), nullable=True),
    sa.Column('answer_excerpt', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['prompt_tracking_id'], ['prompt_tracking.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_check_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_check_snapshots_checked_at'), ['checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_check_snapshots_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_check_snapshots_prompt_tracking_id'), ['prompt_tracking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_check_snapshots_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_check_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_check_snapshots_user_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_check_snapshots_prompt_tracking_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_check_snapshots_client_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_check_snapshots_checked_at'))

    op.drop_table('prompt_check_snapshots')
    # ### end Alembic commands ###
