"""Add workspace logo and prompt tracking fields

Revision ID: 75e0af213b5d
Revises: 19303c408a51
Create Date: 2026-04-05 20:22:53.525706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e0af213b5d'
down_revision = '19303c408a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_filename', sa.String(length=255), nullable=True))

    with op.batch_alter_table('prompt_tracking', schema=None) as batch_op:
        batch_op.alter_column('prompt_score',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('score_band',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('opportunity_label',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('brand_position',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('source_support',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_tracking', schema=None) as batch_op:
        batch_op.alter_column('source_support',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('brand_position',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('opportunity_label',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('score_band',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('prompt_score',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('logo_filename')

    # ### end Alembic commands ###
