"""Add ShopifyConnection table

Revision ID: 8db89666f708
Revises: 75e0af213b5d
Create Date: 2026-05-08 23:34:24.944156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db89666f708'
down_revision = '75e0af213b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopify_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('shop_domain', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('shop_meta', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_shopify_user_client')
    )
    with op.batch_alter_table('shopify_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopify_connections_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shopify_connections_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopify_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopify_connections_user_id'))
        batch_op.drop_index(batch_op.f('ix_shopify_connections_client_id'))

    op.drop_table('shopify_connections')
    # ### end Alembic commands ###
