"""add marketplace_presences table

Revision ID: 94f022959110
Revises: 6d8a28a2e2b5
Create Date: 2026-05-09 06:21:32.390665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f022959110'
down_revision = '6d8a28a2e2b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_presences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('marketplace', sa.String(length=40), nullable=False),
    sa.Column('shop_name', sa.String(length=255), nullable=True),
    sa.Column('shop_url', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('last_visibility_score', sa.Integer(), nullable=True),
    sa.Column('last_audit_payload', sa.JSON(), nullable=True),
    sa.Column('last_audited_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketplace_presences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_presences_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_presences_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_presences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_presences_user_id'))
        batch_op.drop_index(batch_op.f('ix_marketplace_presences_client_id'))

    op.drop_table('marketplace_presences')
    # ### end Alembic commands ###
