"""rewrite referral schema for 25 percent paid model

Revision ID: a0b17aa51f73
Revises: 40a9ccb99afa
Create Date: 2026-05-09 16:15:43.967410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b17aa51f73'
down_revision = '40a9ccb99afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referred_payment_usd', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('reward_credits_referrer', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('stripe_event_ref', sa.String(length=120), nullable=True))
        batch_op.drop_column('reward_amount_referrer')
        batch_op.drop_column('reward_amount_referred')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward_amount_referred', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('reward_amount_referrer', sa.INTEGER(), nullable=False))
        batch_op.drop_column('stripe_event_ref')
        batch_op.drop_column('reward_credits_referrer')
        batch_op.drop_column('referred_payment_usd')

    # ### end Alembic commands ###
