"""rewrite referral schema for 25 percent paid model

Revision ID: a0b17aa51f73
Revises: 40a9ccb99afa
Create Date: 2026-05-09 16:15:43.967410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b17aa51f73'
down_revision = '40a9ccb99afa'
branch_labels = None
depends_on = None


def upgrade():
    # Detect whether the legacy columns are still present so we can
    # backfill data before dropping them. Production deploys with
    # existing referral rows go through the data-copy branch; fresh
    # dev DBs (no rows, columns already in target shape) skip it.
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing = [c['name'] for c in inspector.get_columns('referrals')]
    has_legacy = 'reward_amount_referrer' in existing

    # 1. Add the new columns. server_default='0' on the NOT NULL int
    #    so existing rows pick up a sensible default instead of
    #    failing the SQLite ALTER TABLE on a row count > 0.
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referred_payment_usd', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('reward_credits_referrer', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('stripe_event_ref', sa.String(length=120), nullable=True))

    # 2. Backfill — copy legacy referrer rewards into the new shape,
    #    estimate the implied paid value as 4× the credits (since 25%
    #    payout rate), and translate `completed` → `rewarded` status.
    if has_legacy:
        op.execute("""
            UPDATE referrals
            SET reward_credits_referrer = COALESCE(reward_amount_referrer, 0),
                referred_payment_usd = CASE
                    WHEN reward_amount_referrer > 0 THEN reward_amount_referrer * 4.0
                    ELSE NULL
                END,
                status = CASE WHEN status = 'completed' THEN 'rewarded' ELSE status END,
                rewarded_at = CASE
                    WHEN status IN ('completed', 'rewarded')
                    THEN COALESCE(rewarded_at, qualified_at, created_at)
                    ELSE rewarded_at
                END
        """)

    # 3. Drop the legacy columns now that data is preserved.
    if has_legacy:
        with op.batch_alter_table('referrals', schema=None) as batch_op:
            batch_op.drop_column('reward_amount_referrer')
            batch_op.drop_column('reward_amount_referred')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward_amount_referred', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('reward_amount_referrer', sa.INTEGER(), nullable=False))
        batch_op.drop_column('stripe_event_ref')
        batch_op.drop_column('reward_credits_referrer')
        batch_op.drop_column('referred_payment_usd')

    # ### end Alembic commands ###
