"""add user.extra_workspaces

Revision ID: c12136a63deb
Revises: d9d767cbdb1d
Create Date: 2026-05-09 08:02:31.919012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12136a63deb'
down_revision = 'd9d767cbdb1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_workspaces', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('extra_workspaces')

    # ### end Alembic commands ###
