"""add user_modules table

Revision ID: c319d6520e90
Revises: 7561ba78d568
Create Date: 2026-05-09 19:44:13.021097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c319d6520e90'
down_revision = '7561ba78d568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_slug', sa.String(length=50), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=120), nullable=True),
    sa.Column('stripe_subscription_item_id', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_item_id')
    )
    with op.batch_alter_table('user_modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_modules_module_slug'), ['module_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_modules_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_modules_stripe_subscription_id'), ['stripe_subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_modules_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_modules_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_modules_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_user_modules_status'))
        batch_op.drop_index(batch_op.f('ix_user_modules_module_slug'))

    op.drop_table('user_modules')
    # ### end Alembic commands ###
