"""add google_search_console_connections table

Revision ID: c5a659174965
Revises: 5a7535e7f9bb
Create Date: 2026-05-09 10:37:26.304855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a659174965'
down_revision = '5a7535e7f9bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_search_console_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('site_url', sa.String(length=500), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('last_sync_payload', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_gsc_user_client')
    )
    with op.batch_alter_table('google_search_console_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_google_search_console_connections_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_google_search_console_connections_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_search_console_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_google_search_console_connections_user_id'))
        batch_op.drop_index(batch_op.f('ix_google_search_console_connections_client_id'))

    op.drop_table('google_search_console_connections')
    # ### end Alembic commands ###
