"""add brand kit fields to client

Revision ID: c67f89c5d1a9
Revises: e342edacdd68
Create Date: 2026-05-09 15:58:41.702102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c67f89c5d1a9'
down_revision = 'e342edacdd68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_audience', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('brand_services', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('brand_differentiators', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('brand_voice', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('brand_personality', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('brand_avoid', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('brand_primary_color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('brand_secondary_color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('brand_accent_color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('brand_typography', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('brand_imagery_direction', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('brand_kit_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('brand_kit_updated_at')
        batch_op.drop_column('brand_imagery_direction')
        batch_op.drop_column('brand_typography')
        batch_op.drop_column('brand_accent_color')
        batch_op.drop_column('brand_secondary_color')
        batch_op.drop_column('brand_primary_color')
        batch_op.drop_column('brand_avoid')
        batch_op.drop_column('brand_personality')
        batch_op.drop_column('brand_voice')
        batch_op.drop_column('brand_differentiators')
        batch_op.drop_column('brand_services')
        batch_op.drop_column('brand_audience')

    # ### end Alembic commands ###
