"""add calcom_connections

Revision ID: e342edacdd68
Revises: 330f7f6293f5
Create Date: 2026-05-09 15:54:15.877056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e342edacdd68'
down_revision = '330f7f6293f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calcom_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('last_payload', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_calcom_user_client')
    )
    with op.batch_alter_table('calcom_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calcom_connections_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calcom_connections_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calcom_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calcom_connections_user_id'))
        batch_op.drop_index(batch_op.f('ix_calcom_connections_client_id'))

    op.drop_table('calcom_connections')
    # ### end Alembic commands ###
