"""add interest_signups table

Revision ID: e40dacf2ae69
Revises: e75a64bf4b57
Create Date: 2026-05-10 11:47:50.698924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40dacf2ae69'
down_revision = 'e75a64bf4b57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interest_signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('use_case', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('utm_source', sa.String(length=120), nullable=True),
    sa.Column('utm_medium', sa.String(length=120), nullable=True),
    sa.Column('utm_campaign', sa.String(length=120), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(), nullable=True),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interest_signups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interest_signups_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_interest_signups_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_interest_signups_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interest_signups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interest_signups_status'))
        batch_op.drop_index(batch_op.f('ix_interest_signups_email'))
        batch_op.drop_index(batch_op.f('ix_interest_signups_created_at'))

    op.drop_table('interest_signups')
    # ### end Alembic commands ###
