"""add module-2 and module-3 connector tables

Revision ID: e75a64bf4b57
Revises: c319d6520e90
Create Date: 2026-05-09 20:15:04.725975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75a64bf4b57'
down_revision = 'c319d6520e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bigcommerce_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('store_hash', sa.String(length=120), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('store_meta', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_bigcommerce_user_client')
    )
    with op.batch_alter_table('bigcommerce_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bigcommerce_connections_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bigcommerce_connections_user_id'), ['user_id'], unique=False)

    op.create_table('framer_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=120), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('project_meta', sa.JSON(), nullable=True),
    sa.Column('collections_cache', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_framer_user_client')
    )
    with op.batch_alter_table('framer_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_framer_connections_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_framer_connections_user_id'), ['user_id'], unique=False)

    op.create_table('shopline_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('store_handle', sa.String(length=120), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('shop_meta', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_shopline_user_client')
    )
    with op.batch_alter_table('shopline_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopline_connections_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shopline_connections_user_id'), ['user_id'], unique=False)

    op.create_table('squarespace_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('site_meta', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_squarespace_user_client')
    )
    with op.batch_alter_table('squarespace_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_squarespace_connections_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_squarespace_connections_user_id'), ['user_id'], unique=False)

    op.create_table('wix_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.String(length=120), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('site_meta', sa.JSON(), nullable=True),
    sa.Column('collections_cache', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_wix_user_client')
    )
    with op.batch_alter_table('wix_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wix_connections_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wix_connections_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wix_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wix_connections_user_id'))
        batch_op.drop_index(batch_op.f('ix_wix_connections_client_id'))

    op.drop_table('wix_connections')
    with op.batch_alter_table('squarespace_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_squarespace_connections_user_id'))
        batch_op.drop_index(batch_op.f('ix_squarespace_connections_client_id'))

    op.drop_table('squarespace_connections')
    with op.batch_alter_table('shopline_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopline_connections_user_id'))
        batch_op.drop_index(batch_op.f('ix_shopline_connections_client_id'))

    op.drop_table('shopline_connections')
    with op.batch_alter_table('framer_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_framer_connections_user_id'))
        batch_op.drop_index(batch_op.f('ix_framer_connections_client_id'))

    op.drop_table('framer_connections')
    with op.batch_alter_table('bigcommerce_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bigcommerce_connections_user_id'))
        batch_op.drop_index(batch_op.f('ix_bigcommerce_connections_client_id'))

    op.drop_table('bigcommerce_connections')
    # ### end Alembic commands ###
