"""add email campaigns + recipients tables

Revision ID: fb26cf3a7639
Revises: e40dacf2ae69
Create Date: 2026-05-10 11:54:26.158521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb26cf3a7639'
down_revision = 'e40dacf2ae69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('audience_filter', sa.JSON(), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_campaigns_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_campaigns_status'), ['status'], unique=False)

    op.create_table('email_campaign_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['email_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_campaign_recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_campaign_recipients_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_campaign_recipients_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_campaign_recipients_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_campaign_recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_campaign_recipients_status'))
        batch_op.drop_index(batch_op.f('ix_email_campaign_recipients_email'))
        batch_op.drop_index(batch_op.f('ix_email_campaign_recipients_campaign_id'))

    op.drop_table('email_campaign_recipients')
    with op.batch_alter_table('email_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_email_campaigns_created_at'))

    op.drop_table('email_campaigns')
    # ### end Alembic commands ###
